project_id: 559101
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: '**/Resources.resx'
    translation: '/%original_path%/Resources.%locale%.resx'
    skip_untranslated_strings: true
