# This workflow will build and test a Windows Forms desktop application built with .NET

name: .NET Application Build

on:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string
      artifact_name:
        required: true
        type: string

jobs:
  build:
    runs-on: windows-2019    # For a list of available runner types, refer to https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: PasteIntoFile.sln
      Project_Directory: PasteIntoFile

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      ## Install the .NET Core workload
      ## This is not required since the windows-2019 runner comes with pre-installed .NET Framework
      #- name: Install .NET Core
      #  uses: actions/setup-dotnet@v1
      #  with:
      #    dotnet-version: 5.0.x
      
      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
      
      # Build the app
      - name: Build
        run: msbuild /p:Configuration=${{ inputs.configuration }}
      
      # Upload the binary: https://github.com/marketplace/actions/upload-a-build-artifact
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ env.Project_Directory }}\bin\${{ inputs.Configuration }}
    
